const TOPICS={7:{geometry:[['G7-03','משפט פיתגורס — מציאת צלע',1],['G7-04','זוויות — חישוב זווית חסרה',1]],algebra:[['A7-03','משוואות מדרגה ראשונה',1]],numeric:[['N7-06','חזקות: (−a)ⁿ לעומת −aⁿ',1]],uncertainty:[]},8:{geometry:[],algebra:[],numeric:[['N8-04','אחוזים — מצבים סטטיים',1],['N8-05','אחוזים — מצבים דינמיים',1],['N8-02','פרופורציה',1]],uncertainty:[['U8-01','ממוצע, חציון, טווח',1]]}};
const generators={};
function grade(){return +document.getElementById('sg').value}
function domain(){return document.getElementById('sd').value}
function onGrade(){document.getElementById('gradeBadge').textContent={7:'כיתה ז׳',8:'כיתה ח׳'}[grade()]||'כיתה ז׳';onDomain()}
function onDomain(){let s=document.getElementById('st');s.innerHTML='';let g=TOPICS[grade()]||TOPICS[7];let list=g[domain()]||[];if(!list.length){let o=document.createElement('option');o.value='';o.textContent='אין נושאים זמינים';s.appendChild(o);return}list.forEach(t=>{let o=document.createElement('option');o.value=t[0];o.textContent=t[1];s.appendChild(o)})}
function generate(){let id=document.getElementById('st').value;if(generators[id])generators[id]();else document.getElementById('out').innerHTML='<div class="qcard wip">נושא זה עדיין נעול או בפיתוח לפי חומרי המקור הקיימים.</div>'}
function setMainTitle(cls,topicLabel){let el=document.getElementById('mainTitle');if(!el)return;let domainName=cls==='geo'?'גאומטריה':cls==='alg'?'אלגברה':cls==='unc'?'אי־ודאות':'תחום מספרי';el.textContent=domainName+' — '+topicLabel.replace(/\s*—\s*מנוע (מלא|חדש)\s*✦?\s*$/,'');el.style.display='block'}
function renderCard(id,title,svg,q,a,cls='num'){let cid='q'+Date.now(),aid='a'+Date.now(),gradeLabel=id.includes('8')?'כיתה ח׳':'כיתה ז׳',domainLabel=cls==='geo'?'גאומטריה':cls==='alg'?'אלגברי':cls==='unc'?'אי-ודאות':'מספרי';setMainTitle(cls,title);let html='<div class="qcard" id="'+cid+'"><div class="qmeta"><span class="tag '+cls+'">'+gradeLabel+'</span><span class="tag '+cls+'">'+domainLabel+'</span></div>'+(svg?'<div class="diagram">'+svg+'</div>':'')+'<div class="qtext">'+q+'</div><button class="btn-ans" onclick="document.getElementById(\''+aid+'\').classList.toggle(\'open\')">הצג פתרון</button><div class="answer" id="'+aid+'">'+a+'</div><div class="expbar"><button class="btn-exp" onclick="copyImg(\''+cid+'\',this)">העתק כתמונה</button><button class="btn-exp" onclick="dlPNG(\''+cid+'\',this)">PNG</button><button class="btn-exp" onclick="window.print()">הדפס</button><span class="expstat" id="st-'+cid+'"></span></div></div>';document.getElementById('out').innerHTML=html;renderMathInElement(document.getElementById('out'),{delimiters:[{left:'$$',right:'$$',display:true},{left:'$',right:'$',display:false}],throwOnError:false})}
